### ISSUE TITLE
config gets randomly cleared

### ISSUE THREAD

**Issue by aaronjensen** [1995eaton/chromium-vim#198]
My config is here: https://gist.github.com/aaronjensen/90a959239260d619d67b

Twice in the last couple of days it was cleared in cvim. My gist was still in the sync section, so clicking "sync" brought it back. I don't have a repro for this unfortunately :(

**Comment by 1995eaton** [comment]
This was most likely due to one of my changes to the way cVim settings work ([see here](https://github.com/1995eaton/chromium-vim/issues/191) for another description of the issue and a way to get your old config back). This bug should only occur once across one of the cVim updates, and shouldn't continue to be a problem. Let me know if this issue occurs again and I'll look into it some more.

**Comment by aaronjensen** [comment]
It has happened several times on my home machine.

**Comment by aaronjensen** [comment]
`chrome.storage.local.get('settings', function(e) { console.log(e.settings.MAPPINGS); })` didn't do anything btw, but since I have sync set up, I can just click sync and my config comes back.

What happens if it attempts to sync automatically (autoupdategist) while i'm offline? Could that wipe it?

**Comment by aaronjensen** [comment]
I did see a bunch of this in the console:

```
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.addFrame (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:67:26)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14extensions::uncaught_exception_handler:8 handler
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14extensions::uncaught_exception_handler:8 handler
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
2extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.addFrame (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:67:26)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.addFrame (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:67:26)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.addFrame (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:67:26)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at Object._.injectCSS (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:542:37)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'id' of undefined
    at Object._.setIconEnabled (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:632:24)
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/actions.js:708:14
    at chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/background_scripts/main.js:103:56
```

**Comment by y2kbugger** [comment]
I don't have autosync enabled, I have notice that it get cleared randomly, and that it comes back when refreshing the page

**Comment by primeos** [comment]
> I don't have autosync enabled, I have notice that it get cleared randomly, and that it comes back when refreshing the page

Same here, thanks for the hint I never tried refreshing the page - that helps a lot^^.

Since I refreshed the page (~ 3days ago) my config didn't get cleared.
I tried several things like restarting chromium, killing all processes at once (also with SIGKILL (-9) trying to simulate a crash), disabling and re enabling the extension but I couldn't find a way to reproduce this. Any ideas what could cause this?
I normally only (soft) restart for kernel updates (kexec) and chromium may run for several days straight (I have to restart some times - seems like there are some memory leeks...).

@aaronjensen could you also try refreshing the page if it happens again?

> This bug should only occur once across one of the cVim updates, and shouldn't continue to be a problem. Let me know if this issue occurs again and I'll look into it some more.

@1995eaton I'm a new cVim user i. e. I didn't update even once but my config got cleared ~3-5 Times while using cVim for about ~1.5 months now. Since refreshing helps could there be some problems loading or rendering the config?

Chromium-Version: 48.0.2564.82 (64-bit)
cVim-Version: 1.2.81
OS: Gentoo (GNU/Linux)

**Comment by tecfu** [comment]
I'm having the same issue - my config won't even save. Ubuntu 14.04.4 / Chrome Version 49.0.2623.112

I think what I'm going to do is hardcode my own config into the downloadable source on github - and reinstall.

**Comment by primeos** [comment]
@1995eaton Should be fixed by now, at least it didn't happen to me since ~May and I can't reproduce it anymore by reloading the settings page - ty for fixing :)

I think we can safely close this issue ;)
