### ISSUE TITLE
Can't save settings and saw error

### ISSUE THREAD

**Issue by ppwwyyxx** [1995eaton/chromium-vim#435]
I'm using a github version downloaded just now. 
The save button doesn't work: when I restarted chromium, no settings are there.
And I saw the following error from console:
```
extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: Object.unobserve is not a function
    at setupSettingsObserver (chrome-extension://geekjbonlpnfnkfgagflggmmljdejjom/background_scripts/options.js:22:10)
    at Object.Options.saveSettings (chrome-extension://geekjbonlpnfnkfgagflggmmljdejjom/background_scripts/options.js:104:3)
    at Object.Options.updateBlacklistsMappings (chrome-extension://geekjbonlpnfnkfgagflggmmljdejjom/background_scripts/options.js:174:11)
    at Object.<anonymous> (chrome-extension://geekjbonlpnfnkfgagflggmmljdejjom/background_scripts/options.js:207:8)
    at chrome-extension://geekjbonlpnfnkfgagflggmmljdejjom/background_scripts/options.js:200:31
```

I think it's because `Object.observe` is deprecated: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe.

I'm using Chromium Version 50.0.2661.75 (64-bit)

**Comment by 1995eaton** [comment]
Should be fixed in the latest release
